import { Question, QuestionSet, UserProgress, SyncLog, PlatformStats } from './types';
import scrapedJson from './scraped_data.json';

// Base initial dataset
const baseSets: QuestionSet[] = [
  // LATEST WEDNESDAY STARTERS 176
  {
    id: 'starters-176',
    title: 'CodeChef Starters 176 (Div 1, Div 2, Div 3, Div 4)',
    category: 'wednesday',
    eventDate: '2026-03-04',
    contestCode: 'START176',
    divisions: ['div1', 'div2', 'div3', 'div4'],
    sourceUrl: 'https://www.codechef.com/START176',
    externalId: 'wednesday-start176',
    description: 'Weekly Wednesday rated contest across all four divisions with algorithmic, greedy, mathematical, and DP challenges.',
    createdAt: '2026-03-04T20:00:00Z',
    questions: [
      // Div 4 Questions
      {
        id: 'start176-p1',
        questionSetId: 'starters-176',
        problemCode: 'XLSL',
        title: 'XL or Small',
        difficulty: 'Easy',
        rating: 450,
        tags: ['Basic Math', 'Conditionals', 'Div 4'],
        problemUrl: 'https://www.codechef.com/START176D/problems/XLSL',
        editorialUrl: 'https://discuss.codechef.com/tags/start176',
        category: 'wednesday',
        division: 'div4',
        position: 1,
        successfulSubmissions: 7850,
        accuracy: 82,
        points: 100,
        createdAt: '2026-03-04T20:00:00Z',
      },
      {
        id: 'start176-p2',
        questionSetId: 'starters-176',
        problemCode: 'RUNCH',
        title: 'Run for Chef',
        difficulty: 'Easy',
        rating: 720,
        tags: ['Arrays', 'Implementation', 'Div 4'],
        problemUrl: 'https://www.codechef.com/START176D/problems/RUNCH',
        editorialUrl: 'https://discuss.codechef.com/tags/start176',
        category: 'wednesday',
        division: 'div4',
        position: 2,
        successfulSubmissions: 5410,
        accuracy: 68,
        points: 100,
        createdAt: '2026-03-04T20:00:00Z',
      },
      {
        id: 'start176-p3',
        questionSetId: 'starters-176',
        problemCode: 'MAXEQL',
        title: 'Make Them Equal Again',
        difficulty: 'Easy',
        rating: 980,
        tags: ['Greedy', 'Prefix Sums', 'Div 4', 'Div 3'],
        problemUrl: 'https://www.codechef.com/START176D/problems/MAXEQL',
        editorialUrl: 'https://discuss.codechef.com/tags/start176',
        category: 'wednesday',
        division: 'div4',
        position: 3,
        successfulSubmissions: 3940,
        accuracy: 54,
        points: 100,
        createdAt: '2026-03-04T20:00:00Z',
      },
      // Div 3 Questions
      {
        id: 'start176-p4',
        questionSetId: 'starters-176',
        problemCode: 'SAMEPAR',
        title: 'Same Parity Swap',
        difficulty: 'Medium',
        rating: 1420,
        tags: ['Constructive', 'Bitwise', 'Div 3'],
        problemUrl: 'https://www.codechef.com/START176C/problems/SAMEPAR',
        editorialUrl: 'https://discuss.codechef.com/tags/start176',
        category: 'wednesday',
        division: 'div3',
        position: 1,
        successfulSubmissions: 2840,
        accuracy: 45,
        points: 100,
        createdAt: '2026-03-04T20:00:00Z',
      },
      {
        id: 'start176-p5',
        questionSetId: 'starters-176',
        problemCode: 'SUBORXOR',
        title: 'Subarray OR vs XOR',
        difficulty: 'Medium',
        rating: 1580,
        tags: ['Bitmask', 'Two Pointers', 'Div 3', 'Div 2'],
        problemUrl: 'https://www.codechef.com/START176C/problems/SUBORXOR',
        editorialUrl: 'https://discuss.codechef.com/tags/start176',
        category: 'wednesday',
        division: 'div3',
        position: 2,
        successfulSubmissions: 1720,
        accuracy: 38,
        points: 100,
        createdAt: '2026-03-04T20:00:00Z',
      },
      // Div 2 Questions
      {
        id: 'start176-p6',
        questionSetId: 'starters-176',
        problemCode: 'TREECOL',
        title: 'Tree Coloring Minimums',
        difficulty: 'Medium',
        rating: 1780,
        tags: ['Trees', 'Tree DP', 'Div 2'],
        problemUrl: 'https://www.codechef.com/START176B/problems/TREECOL',
        editorialUrl: 'https://discuss.codechef.com/tags/start176',
        category: 'wednesday',
        division: 'div2',
        position: 1,
        successfulSubmissions: 940,
        accuracy: 29,
        points: 100,
        createdAt: '2026-03-04T20:00:00Z',
      },
      {
        id: 'start176-p7',
        questionSetId: 'starters-176',
        problemCode: 'GRIDPATHX',
        title: 'K-Step Grid Paths',
        difficulty: 'Hard',
        rating: 1950,
        tags: ['Dynamic Programming', 'Combinatorics', 'Div 2', 'Div 1'],
        problemUrl: 'https://www.codechef.com/START176B/problems/GRIDPATHX',
        editorialUrl: 'https://discuss.codechef.com/tags/start176',
        category: 'wednesday',
        division: 'div2',
        position: 2,
        successfulSubmissions: 530,
        accuracy: 22,
        points: 100,
        createdAt: '2026-03-04T20:00:00Z',
      },
      // Div 1 Questions
      {
        id: 'start176-p8',
        questionSetId: 'starters-176',
        problemCode: 'SEGTREEEX',
        title: 'Dynamic Range Inversion Queries',
        difficulty: 'Hard',
        rating: 2350,
        tags: ['Segment Trees', 'Fenwick Tree', 'Div 1'],
        problemUrl: 'https://www.codechef.com/START176A/problems/SEGTREEEX',
        editorialUrl: 'https://discuss.codechef.com/tags/start176',
        category: 'wednesday',
        division: 'div1',
        position: 1,
        successfulSubmissions: 180,
        accuracy: 16,
        points: 100,
        createdAt: '2026-03-04T20:00:00Z',
      },
    ],
  },

  // MONDAY DSA WEEKLY SET
  {
    id: 'monday-dsa-w10-2026',
    title: 'Monday DSA Challenge: Binary Trees & Tree DP Mastery',
    category: 'monday',
    eventDate: '2026-03-02',
    sourceUrl: 'https://www.codechef.com/practice',
    externalId: 'monday-2026-03-02',
    description: 'Weekly curated Monday DSA training problems covering Tree Traversals, Lowest Common Ancestor, Diameter, and DP on Subtrees.',
    createdAt: '2026-03-02T09:00:00Z',
    questions: [
      {
        id: 'mon-w10-q1',
        questionSetId: 'monday-dsa-w10-2026',
        problemCode: 'TREEROOT',
        title: 'Root of the Problem',
        difficulty: 'Easy',
        rating: 1100,
        tags: ['Trees', 'Math', 'Data Structures'],
        problemUrl: 'https://www.codechef.com/problems/TREEROOT',
        editorialUrl: 'https://discuss.codechef.com/problems/TREEROOT',
        category: 'monday',
        division: 'all',
        position: 1,
        successfulSubmissions: 12400,
        accuracy: 64,
        points: 100,
        createdAt: '2026-03-02T09:00:00Z',
      },
      {
        id: 'mon-w10-q2',
        questionSetId: 'monday-dsa-w10-2026',
        problemCode: 'TALCA',
        title: 'Lowest Common Ancestor Queries',
        difficulty: 'Medium',
        rating: 1620,
        tags: ['Binary Lifting', 'LCA', 'Trees'],
        problemUrl: 'https://www.codechef.com/problems/TALCA',
        editorialUrl: 'https://discuss.codechef.com/problems/TALCA',
        category: 'monday',
        division: 'all',
        position: 2,
        successfulSubmissions: 3950,
        accuracy: 42,
        points: 100,
        createdAt: '2026-03-02T09:00:00Z',
      },
      {
        id: 'mon-w10-q3',
        questionSetId: 'monday-dsa-w10-2026',
        problemCode: 'SUBTREEDP',
        title: 'Max Weight Independent Set on Trees',
        difficulty: 'Hard',
        rating: 2050,
        tags: ['Tree DP', 'Dynamic Programming', 'DFS'],
        problemUrl: 'https://www.codechef.com/problems/SUBTREEDP',
        editorialUrl: 'https://discuss.codechef.com/problems/SUBTREEDP',
        category: 'monday',
        division: 'all',
        position: 3,
        successfulSubmissions: 1180,
        accuracy: 27,
        points: 100,
        createdAt: '2026-03-02T09:00:00Z',
      },
      {
        id: 'mon-w10-q4',
        questionSetId: 'monday-dsa-w10-2026',
        problemCode: 'CENTROID',
        title: 'Centroid Decomposition Explorer',
        difficulty: 'Hard',
        rating: 2400,
        tags: ['Centroid Decomposition', 'Divide and Conquer'],
        problemUrl: 'https://www.codechef.com/problems/CENTROID',
        editorialUrl: 'https://discuss.codechef.com/problems/CENTROID',
        category: 'monday',
        division: 'all',
        position: 4,
        successfulSubmissions: 610,
        accuracy: 19,
        points: 100,
        createdAt: '2026-03-02T09:00:00Z',
      },
    ],
  },
];

// Helper to merge scraped JSON if available
function getInitialSets(): QuestionSet[] {
  try {
    if (scrapedJson && scrapedJson.sets && scrapedJson.sets.length > 0) {
      // Return fresh scraped sets combined with base sets
      const merged = [...(scrapedJson.sets as unknown as QuestionSet[])];
      for (const base of baseSets) {
        if (!merged.some(m => m.id === base.id)) {
          merged.push(base);
        }
      }
      return merged;
    }
  } catch {
    // fallback
  }
  return baseSets;
}

export const initialQuestionSets: QuestionSet[] = getInitialSets();

export const initialSyncLogs: SyncLog[] = [
  {
    id: 'log-1',
    syncType: 'scraper',
    category: 'wednesday',
    status: 'success',
    message: 'Scraped CodeChef Starters 176 (Div 1, Div 2, Div 3, Div 4) successfully.',
    questionsFound: 28,
    questionsAdded: 28,
    timestamp: '2026-03-04T22:30:00Z',
  },
  {
    id: 'log-2',
    syncType: 'auto',
    category: 'monday',
    status: 'success',
    message: 'Synchronized Monday DSA Week 10 (Binary Trees & Tree DP).',
    questionsFound: 4,
    questionsAdded: 4,
    timestamp: '2026-03-02T10:00:00Z',
  },
];
